### PR TITLE
support for deb installed roseus scenario 

### PR DESCRIPTION
**Pull request by k-okada**
this patch reqruies -> https://github.com/euslisp/EusLisp/pull/239

Finally I had conclusion that https://github.com/jsk-ros-pkg/jsk_roseus/pull/464 is ok. But did you check if this works when roseus is installed deb?

1. https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_warning/battery_warning.l consumes 15-20% of cpu, because of `/diagnostics_agg`, but I found that if we compile `DiagnosticsArray.l` it becomes 5-8%.
2. so we'd like set compile-message as default behavior, but adding `(defparameter ros::*compile-message* t)`  may cause trouble, for example if someone try to run the program, it runs `.l` compile process and would takes sometime to start process, that 's hard to observe , I think.
3. so I'd like to compile message during package compile time
4.  I'm not sure if current 
```
;; see https://github.com/jsk-ros-pkg/jsk_roseus/pull/464 for discussion                                    
(defparameter ros::*compile-message* nil) ;; compile msg/srv when loaded                                    
(defparameter ros::*compile* nil)         ;; compile msg/srv and files start with package://
```
is good design, do we have any problem if we set
```
;; see https://github.com/jsk-ros-pkg/jsk_roseus/pull/464 for discussion                                    
(defparameter ros::*compile-message* nil) ;; compile msg/srv when loaded                                    
(defparameter ros::*compile* nil)         ;; compile files start with package://
```
???

### CODE REVIEW

**Comment by furushchev** [comment]
> But did you check if this works when roseus is installed deb?

Oh, no. For both jsk-ros-pkg#464 and this pull reuqest, I now tried and confirmed that they do not work.

```bash
docker run --rm -it osrf/ros:indigo-desktop /bin/bash
apt update
apt install ros-indigo-roseus wget sudo python-catkin-tools

# compile euslisp from source
mkdir -p ~/euslisp/src && cd ~/euslisp/src
wstool init
wget https://raw.githubusercontent.com/jsk-ros-pkg/jsk_roseus/master/setup_upstream.sh
chmod +x setup_upstream.sh
./setup_upstream.sh -w ..
catkin config --init --install
cd euslisp/jskeus
git remote add k-okada https://github.com/k-okada/Euslisp
git fetch k-okada
git checkout compile_file_write_protect
catkin b
cd ../../../install/share/euslisp
cp -r . /opt/ros/indigo/share/euslisp/

wget https://github.com/jsk-ros-pkg/jsk_roseus/pull/464.patch -O /tmp/roseus.patch
cd /opt/ros/indigo/share
patch -p1 < /tmp/roseus.patch
adduser temp
adduser temp sudo
su - temp
source /opt/ros/indigo/setup.bash
mkdir -p ~/catkin_ws/src && cd ~/catkin_ws
catkin init && catkin build
source devel/setup.bash
roseus
(setq ros::*compile-message* t)
(ros::load-ros-manifest "sensor_msgs")
/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error:  cannot open /opt/ros/indigo/share/roseus/ros/std_msgs/msg/Float32MultiArray.c in (compiler:compile-file-if-src-newer dirfile (format nil "~A/~A_~A" dir pkg fname))
5.E1-ROS:irteusgl$ 5.irteusgl$ [ INFO] [1492178776.828312542]: cell* ROSEUS_EXIT(context*, int, cell**)

^C

wget https://github.com/furushchev/jsk_roseus/pull/1.patch -O /tmp/furushchev_roseus.patch
cd /opt/ros/indigo/share
sudo patch -p1 < /tmp/furushchev_roseus.patch
source ~/catkin_ws/devel/setup.bash
roseus
(setq ros::*compile-message* t)
(ros::load-ros-manifest "sensor_msgs")
/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error:  cannot open /opt/ros/indigo/share/roseus/ros/std_msgs/msg/Float32MultiArray.c in (compiler:compile-file-if-src-newer dirfile (format nil "~A/~A_~A" dir pkg fname))

```

**Comment by k-okada** [comment]
did you import https://github.com/euslisp/EusLisp/pull/239 ?
easiest "workaround" is compile euslisp and copy eusgl to /opt/ros/..

--
◉ Kei Okada


2017-04-14 23:07 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by k-okada** [comment]
MEMO: I have compiled only `diagnostic_msgs` on `pr1040` using `compile_msgs.sh`, once you update `roseus`, I think you can use compiled message file only for `diagnostic_msgs`, and for now, I think it'S ok.
```
applications@pr1040s:~/ros/hydro/devel/share/roseus/ros/diagnostic_msgs/msg$ ls
DiagnosticArray.c   DiagnosticStatus.l  compile_msgs.sh~                     diagnostic_msgs_KeyValue.o
DiagnosticArray.h   KeyValue.c          diagnostic_msgs_DiagnosticArray.o    diagnostic_msgs_KeyValue.so
DiagnosticArray.l   KeyValue.h          diagnostic_msgs_DiagnosticArray.so
DiagnosticStatus.c  KeyValue.l          diagnostic_msgs_DiagnosticStatus.o
DiagnosticStatus.h  compile_msgs.sh     diagnostic_msgs_DiagnosticStatus.so
```

**Comment by furushchev** [comment]
@k-okada OK. I have one subtle question about this. Let's short talk offline later.

**Comment by furushchev** [comment]
I talked with @k-okada offine, and decided as followings:

- Conduct beta program to some euslisp users with compiled message version roseus
- This patch and patch at euslisp/jskeus is enough (my patch in roseus is no more necessary.)

**Pull request closed without merging**
